const KEY = {
         LOAD_JOB: "REQUEST_JOBS_DATA",
         LOAD_JOB_SUCCESS: "RECEIVE_JOBS_DATA",
         LOAD_USER_PROFILE:  "REQUEST_USER_DATA",
         LOAD_USER_PROFILE_SUCCESS: "RECEIVE_USER_DATA",
         LOAD_USERS:  "REQUEST_USERS_DATA",
         LOAD_USERS_SUCCESS: "RECEIVE_USERS_DATA",
         LOAD_BOOKINGS:  "REQUEST_BOOKINGS_DATA",
         LOAD_BOOKINGS_SUCCESS: "RECEIVE_BOOKINGS_DATA",
         LOAD_CITIES:  "REQUEST_CITIES_DATA",
         LOAD_CITIES_SUCCESS: "RECEIVE_CITIES_DATA",
};

export default KEY;
